<?php
return [
    [
        'name' => 'Scooter-lim-Danzeri-Simone',
        'slug' => 'scooter-lim-danzeri-simone',
        'type_id' => 1,
        'summary' => 'Questo è il progetto esame per accedere al corso di FullStack Web Development di Boolean Career',
    ],
    [
        'name' => 'htmlcss-hello',
        'slug' => 'htmlcss-hello',
        'type_id' => 1,
        'summary' => 'Primo esercizio di Boolean Career. Si tratta di una pagina statica con la scritta hello world!',
    ],
    [
        'name' => 'html-london-trip',
        'slug' => 'html-london-trip',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'html-css-booleaner',
        'slug' => 'html-css-booleaner',
        'type_id' => 1,
        'summary' => 'Primo esercizio con anche CSS per stile',
    ],
    [
        'name' => 'html-css-tobolist',
        'slug' => 'html-css-tobolist',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'htmlcss-struttura-discord',
        'slug' => 'htmlcss-struttura-discord',
        'type_id' => 1,
        'summary' => 'Esercizio di formazione struttura per futuro esercizio completo di HTML e CSS',
    ],
    [
        'name' => 'htmlcss-discord',
        'slug' => 'htmlcss-discord',
        'type_id' => 1,
        'summary' => 'Prima pagina statica con HTML e CSS',
    ],
    [
        'name' => 'html-css-boolando',
        'slug' => 'html-css-boolando',
        'type_id' => 1,
        'summary' => 'Pagina statica che simula il sito di Zalando',
    ],
    [
        'name' => 'html-css-zoom',
        'slug' => 'html-css-zoom',
        'type_id' => 1,
        'summary' => 'Pagina statica che simula la web app di Zoom',
    ],
    [
        'name' => 'html-css-dropbox',
        'slug' => 'html-css-dropbox',
        'type_id' => 1,
        'summary' => 'Esercizio di più giorni su una pagina statica responsive',
    ],
    [
        'name' => 'html-css-resp-wannabe',
        'slug' => 'html-css-resp-wannabe',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'htmlcss-responsive-layout',
        'slug' => 'htmlcss-responsive-layout',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'html-css-spotify',
        'slug' => 'html-css-spotify',
        'type_id' => 1,
        'summary' => 'Pagina statica responsive della versione web di Spotify',
    ],
    [
        'name' => 'html-css-12bool',
        'slug' => 'html-css-12bool',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'html-css-bootstrap-freelancer',
        'slug' => 'html-css-bootstrap-freelancer',
        'type_id' => 1,
        'summary' => 'Primo utilizzo del framework di Bootstrap',
    ],
    [
        'name' => 'html-css-bootstrap-dashboard',
        'slug' => 'html-css-bootstrap-dashboard',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'js-pwdgen-wannabe',
        'slug' => 'js-pwdgen-wannabe',
        'type_id' => 1,
        'summary' => 'Primo esercizio su JavaScript vanilla. Si tratta di un generatore casuale di password (per nulla sicuro!)',
    ],
    [
        'name' => 'js-biglietto-treno',
        'slug' => 'js-biglietto-treno',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'js-biglietto-treno-form',
        'slug' => 'js-biglietto-treno-form',
        'type_id' => 1,
        'summary' => 'Primo esercizio di JS in cui prendiamo i dati da un form utente',
    ],
    [
        'name' => 'js-fizzbuzz',
        'slug' => 'js-fizzbuzz',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'js-mail-dadi',
        'slug' => 'js-mail-dadi',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'js-lista-spesa',
        'slug' => 'js-lista-spesa',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'js-paliedispari',
        'slug' => 'js-paliedispari',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'js-campominato-grid',
        'slug' => 'js-campominato-grid',
        'type_id' => 1,
        'summary' => 'Preparazione al campo minato',
    ],
    [
        'name' => 'js-campominato-dom',
        'slug' => 'js-campominato-dom',
        'type_id' => 1,
        'summary' => 'Esercizio completo di JS vanilla dove abbiamo simulato una versione più facile e completamente basata sulla fortuna di campo minato',
    ],
    [
        'name' => 'js-simon',
        'slug' => 'js-simon',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'js-our-team',
        'slug' => 'js-our-team',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'js-array-objects-carousel',
        'slug' => 'js-array-objects-carousel',
        'type_id' => 1,
        'summary' => 'Creazione in JS vanilla del carosello con manipolazione del DOM',
    ],
    [
        'name' => 'js-social-posts',
        'slug' => 'js-social-posts',
        'type_id' => 1,
        'summary' => 'Finto blog per post',
    ],
    [
        'name' => 'vue-hello',
        'slug' => 'vue-hello',
        'type_id' => 1,
        'summary' => 'Primo esercizio di avvicinamento al framework di VueJs',
    ],
    [
        'name' => 'vue-slider',
        'slug' => 'vue-slider',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'vue-todolist',
        'slug' => 'vue-todolist',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'vue-boolzapp',
        'slug' => 'vue-boolzapp',
        'type_id' => 1,
        'summary' => 'Esercizio in cui ho simulato la versione web app di Whatsapp. Vi è la possibilità di filtrare i contatti e di mandare e ricevere messaggi custom.',
    ],
    [
        'name' => 'vue-email-list',
        'slug' => 'vue-email-list',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'vite-hello-world',
        'slug' => 'vite-hello-world',
        'type_id' => 1,
        'summary' => 'Primo progetto con il software di Vite',
    ],
    [
        'name' => 'vite-comics',
        'slug' => 'vite-comics',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'vite-yu-gi-ho',
        'slug' => 'vite-yu-gi-ho',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'vite-boolflix',
        'slug' => 'vite-boolflix',
        'type_id' => 1,
        'summary' => '',
    ],
    [
        'name' => 'proj-html-vuejs',
        'slug' => 'proj-html-vuejs',
        'type_id' => 1,
        'summary' => 'Esercizio di mid-term',
    ],
    [
        'name' => 'php-badwords',
        'slug' => 'php-badwords',
        'type_id' => 2,
        'summary' => 'Primo esercizio con PHP plain',
    ],
    [
        'name' => 'php-hotel',
        'slug' => 'php-hotel',
        'type_id' => 2,
        'summary' => '',
    ],
    [
        'name' => 'php-strong-password-generator',
        'slug' => 'php-strong-password-generator',
        'type_id' => 2,
        'summary' => '',
    ],
    [
        'name' => 'php-dischi-json',
        'slug' => 'php-dischi-json',
        'type_id' => 2,
        'summary' => '',
    ],
    [
        'name' => 'DB-first',
        'slug' => 'DB-first',
        'type_id' => 3,
        'summary' => 'Primo esercizio sui database',
    ],
    [
        'name' => 'DB-university',
        'slug' => 'DB-university',
        'type_id' => 3,
        'summary' => '',
    ],
    [
        'name' => 'php-oop-1',
        'slug' => 'php-oop-1',
        'type_id' => 2,
        'summary' => '',
    ],
    [
        'name' => 'php-oop-2',
        'slug' => 'php-oop-2',
        'type_id' => 2,
        'summary' => '',
    ],
    [
        'name' => 'laravel-primi-passi',
        'slug' => 'laravel-primi-passi',
        'type_id' => 2,
        'summary' => 'Primo esercizio di avvicinamento al framework Laravel',
    ],
    [
        'name' => 'laravel-comics',
        'slug' => 'laravel-comics',
        'type_id' => 2,
        'summary' => '',
    ],
    [
        'name' => 'laravel-model-controller',
        'slug' => 'laravel-model-controller',
        'type_id' => 2,
        'summary' => 'primo esercizio su MVC',
    ],
    [
        'name' => 'laravel-migration-seeder',
        'slug' => 'laravel-migration-seeder',
        'type_id' => 2,
        'summary' => '',
    ],
    [
        'name' => 'laravel-dc-comics',
        'slug' => 'laravel-dc-comics',
        'type_id' => 2,
        'summary' => '',
    ],
    [
        'name' => 'laravel-auth',
        'slug' => 'laravel-auth',
        'type_id' => 2,
        'summary' => 'Esercizio in cui ho implementato per la prima volta la funzione di autenticazione',
    ],
    [
        'name' => 'laravel-one-to-many',
        'slug' => 'laravel-one-to-many',
        'type_id' => 2,
        'summary' => 'Esercizio sulla gestione di entità relazionali',
    ],
    [
        'name' => 'laravel-many-to-many',
        'slug' => 'laravel-many-to-many',
        'type_id' => 2,
        'summary' => '',
    ],
    [
        'name' => 'laravel-api',
        'slug' => 'laravel-api',
        'type_id' => 2,
        'summary' => 'Esercizio conclusivo del backend in Boolean sulla creazione e gestione di RestAPI',
    ],
    [
        'name' => 'vite-boolfolio',
        'slug' => 'vite-boolfolio',
        'type_id' => 3,
        'summary' => 'FrontEnd di laravel-api',
    ],
    [
        'name' => 'deliveboo-bo',
        'slug' => 'deliveboo-bo',
        'type_id' => 2,
        'summary' => 'Esame finale in Boolean. Si tratta del Backoffice del sito di Deliveroo. Il tutto protetto da autenticazione e con funzionalità quali aggiungere un ristorante, aggiungere e modificare piatti del menu e la gestione degli ordini'
    ],
    [
        'name' => 'delivebo-fo',
        'summary' => 'delivebo-fo',
        'type_id' => 3,
        'summary' => 'Repository per il Frontoffice della versione web di Deliveroo. Qui gli utenti interessati hanno la possibilità di filtrare i vari ristoranti sulla base di quale cucina preferiscono, creare un carrello con i loro ordini ed infine pagare tramite la piattaforma di Braintree'
    ]
];
